jobs:
  - name: dv-man
    type: manifest
    steps:
      - GET: dv-image
        pull: false
      - GET: dv-opts
      - GET: dv-params
        applyTo:
          - dv-image
      - TASK: managed
      - GET: trigger-dv-man
    on_success:
      - echo 'this is on_success step of dv-man of type manifest'
    on_failure:
      - echo 'this is on_failure step of dv-man of type manifest'

  - name: dv-test
    type: ecsDeploy
    steps:
      - GET: dv-man
      - GET: env-test
      - TASK: managed
    on_success:
      - echo 'this is on_success step of dv-test of type ecsDeploy'

  - name: box-man
    type: manifest
    steps:
      - GET: box-image
        pull: false
      - GET: box-opts
      - GET: box-params
      - TASK: managed

  - name: box-test
    type: ecsDeploy
    steps:
      - GET: box-man
      - GET: env-test
      - TASK: managed

  - name: box-dcl
    type: dclDeploy
    steps:
      - GET: box-man
      - GET: env-dcl
      - TASK: managed

  - name: box-gke
    type: gkeDeploy
    steps:
      - GET: box-man
      - GET: env-gke
      - TASK: managed

  - name: box-prod
    type: ecsDeploy
    steps:
      - GET: box-man
      - GET: env-prod
      - TASK: managed

  - name: multi-manifest
    type:  ecsDeploy
    steps:
      - GET: box-man
      - GET: dv-man
      - GET: env-test
      - TASK: managed

  - name: release-one
    type: release
    options:
      action: minor
    steps:
      - GET: version-resource
      - GET: dv-man
      - TASK: managed

  - name: box-tripub-man
    type: manifest
    steps:
      - GET: box-image
        pull: false
      - GET: box-tripub-opts
      - TASK: managed

  - name: box-tripub
    type: tripubDeploy
    steps:
      - GET: box-tripub-man
      - GET: env-tripub
      - TASK: managed

  - name: infra-provision
    type: runSh
    steps:
      - GET: infra-repo
      - TASK:
        - script: ls
        - script: ./GET/infra-repo/infra-repo/provision.sh
