jobs:
  - name: dv-man
    type: manifest
    steps:
      - IN: dv-image
        pull: false
      - IN: dv-opts
      - IN: dv-params
        applyTo:
          - dv-image
      - TASK: managed
      - IN: trigger-dv-man
    on_success:
      - echo 'this is on_success step of dv-man of type manifest'
    on_failure:
      - echo 'this is on_failure step of dv-man of type manifest'

  - name: dv-man-versionName
    type: manifest
    steps:
      - IN: dv-image
        pull: false
        versionName: latest
      - IN: dv-opts
      - IN: dv-params
        applyTo:
          - dv-image
      - TASK: managed
      - IN: trigger-dv-man

  - name: dv-man-versionNumber
    type: manifest
    steps:
      - IN: dv-image
        pull: false
        versionNumber: 1
      - IN: dv-opts
      - IN: dv-params
        applyTo:
          - dv-image
      - TASK: managed
      - IN: trigger-dv-man

  - name: dv-test
    type: ecsDeploy
    on_start:
      - NOTIFY: slackNotification
    steps:
      - IN: dv-man
      - IN: env-test
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - echo 'this is on_success step of dv-test of type ecsDeploy'
      - NOTIFY: slackNotifcation
    on_failure:
      - NOTIFY: slackNotification

  - name: box-man
    type: manifest
    steps:
      - IN: box-image
        pull: false
      - IN: box-opts
      - IN: box-params
      - TASK: managed

  - name: box-test
    type: ecsDeploy
    steps:
      - IN: box-man
      - IN: env-test
      - TASK: managed
        deployMethod: upgrade

  - name: box-dcl
    type: dclDeploy
    steps:
      - IN: box-man
      - IN: env-dcl
      - TASK: managed

  - name: box-gke
    type: gkeDeploy
    steps:
      - IN: box-man
      - IN: env-gke
      - TASK: managed

  - name: box-prod
    type: ecsDeploy
    steps:
      - IN: box-man
      - IN: env-prod
      - TASK: managed

  - name: multi-manifest
    type:  ecsDeploy
    steps:
      - IN: box-man
      - IN: dv-man
      - IN: env-test
      - TASK: managed
        deployMethod: upgrade

  - name: release-one
    type: release
    steps:
      - IN: version-resource
      - IN: dv-man
      - TASK: managed
        bump: major

  - name: box-tripub-man
    type: manifest
    steps:
      - IN: box-image
        pull: false
      - IN: box-tripub-opts
      - TASK: managed

  - name: box-tripub
    type: tripubDeploy
    steps:
      - IN: box-tripub-man
      - IN: env-tripub
      - TASK: managed

  - name: infra-provision
    type: runSh
    steps:
      - IN: infra-repo
      - TASK:
        - script: ls
        - script: ./GET/infra-repo/infra-repo/provision.sh
