jobs:
  - name: dv-man
    type: manifest
    steps:
      - GET: dv-image
        pull: false
      - GET: dv-opts
      - GET: dv-params
        applyTo:
          - dv-image
      - GET: trigger-dv-man

  - name: dv-test
    type: ecsDeploy
    steps:
      - GET: dv-man
      - GET: env-test

  - name: box-man
    type: manifest
    steps:
      - GET: box-image
        pull: false
      - GET: box-opts
      - GET: box-params

  - name: box-test
    type: ecsDeploy
    steps:
      - GET: box-man
      - GET: env-test

  - name: box-dcl
    type: dclDeploy
    steps:
      - GET: box-man
      - GET: env-dcl

  - name: box-gke
    type: gkeDeploy
    steps:
      - GET: box-man
      - GET: env-gke

  - name: box-prod
    type: ecsDeploy
    steps:
      - GET: box-man
      - GET: env-prod

  - name: multi-manifest
    type:  ecsDeploy
    steps:
      - GET: box-man
      - GET: dv-man
      - GET: env-test

  - name: release-one
    type: release
    options:
      action: minor
    steps:
      - GET: version-resource
      - GET: dv-man

  - name: box-tripub-man
    type: manifest
    steps:
      - GET: box-image
        pull: false
      - GET: box-tripub-opts

  - name: box-tripub
    type: tripubDeploy
    steps:
      - GET: box-tripub-man
      - GET: env-tripub

  - name: infra-provision
    type: runSh
    steps:
      GET: infra-repo
      TASK:
        - script: ls
        - script: ./GET/infra-repo/infra-repo/provision.sh
